---
# via https://github.com/ChrisChinchilla/Openly
# License: https://github.com/ChrisChinchilla/Openly/blob/main/LICENSE


extends: existence
message: "'%s' is an unclear antecedent"
ignorecase: true
level: error
raw:
  - '(?:^[^\w]*|[;-]\s)This\b\s(is|are)\b'
