---
# via https://github.com/ChrisChinchilla/Openly
# License: https://github.com/ChrisChinchilla/Openly/blob/main/LICENSE


extends: existence
message: "Don't start a sentence with '%s'"
ignorecase: true
level: error
action:
  name: edit
  params:
    - remove
    - '.?!'
raw:
  - '(?<=[.;?!]\s)(?:[.-]?\s*)so\b'
