---
# via https://github.com/ChrisChinchilla/Openly
# License: https://github.com/ChrisChinchilla/Openly/blob/main/LICENSE


extends: existence
message: Do not use '%s' at the end of headings
link: https://github.com/Openly/docs/blob/master/STYLE.md#capitalization-and-punctuation
scope: heading
level: warning
raw:
  - '(?:\:|\.)$'
