---
# via https://github.com/ChrisChinchilla/Openly
# License: https://github.com/ChrisChinchilla/Openly/blob/main/LICENSE


message: "Write short sentences (less than 25 words)."
extends: occurrence
link: http://styleguide.mailchimp.com/writing-for-accessibility/#header-3-use-plain-language
scope: sentence
level: warning
max: 25
token: \b(\w+)\b
