---
# via https://github.com/ChrisChinchilla/Openly
# License: https://github.com/ChrisChinchilla/Openly/blob/main/LICENSE


extends: existence
message: "Do not start a paragraph with a 'but'."
level: error
scope: paragraph
action:
  name: remove
  params:
    - remove
    - '.?!'
tokens:
  - ^But
