---
# via https://github.com/ChrisChinchilla/Openly
# License: https://github.com/ChrisChinchilla/Openly/blob/main/LICENSE

extends: existence
message: "Possible future tense."
ignorecase: true
level: warning
tokens:
  - will
  - '[\w][ll]'
  - we are going
  - would-be
  - would be
