# via https://github.com/errata-ai/Readability
# License: https://github.com/errata-ai/readability/blob/main/LICENSE
# Version: https://github.com/errata-ai/readability/releases/tag/v0.1.1

extends: metric
message: "Try to keep the SMOG grade (%s) below 10."
link: https://en.wikipedia.org/wiki/SMOG

formula: |
  1.0430 * math.sqrt((polysyllabic_words * 30.0) / sentences) + 3.1291

condition: "> 10"
