# via https://github.com/errata-ai/Readability
# License: https://github.com/errata-ai/readability/blob/main/LICENSE
# Version: https://github.com/errata-ai/readability/releases/tag/v0.1.1

extends: metric
message: "Try to keep the Gunning-Fog index (%s) below 10."
link: https://en.wikipedia.org/wiki/Gunning_fog_index

formula: |
  0.4 * ((words / sentences) + 100 * (complex_words / words))

condition: "> 10"
