#!/bin/bash

# load the bashrc helper functions
# shellcheck disable=SC2154 # defined in bashrc
__dnb_auto_source "${BASHRC_PATH}"/partials/_functions__helpers/*;

# load the bashrc functions
__dnb_auto_source "${BASHRC_PATH}"/partials/_functions/*;
