#!/bin/bash

# load the bash functions
for FILE in "${BASHRC_PATH}"/_functions/*; do
  set -a
  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
  # see https://github.com/koalaman/shellcheck/wiki/SC1090
  # shellcheck source=/dev/null
  [ -f "${FILE}" ] && source "${FILE}"
  set +a
done
