#!/bin/bash

# a collection of inxi aliases for quick system information
alias sysinfo='inxi -Sxxx'
alias sysinfo-full='inxi -Fxxxz'
alias sysinfo-cpu='inxi -Cxxx'
alias sysinfo-gpu='inxi -Gxxx'
alias sysinfo-mem='inxi -mxxx'			

# more verbosity
alias mv="mv -iv"
alias cp="cp -iv"
