---
################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: "friday"
      time: "23:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - "type:dependencies"
    cooldown:
      default-days: 7
