[[workspace]]
title = "Dashboard"
icon = ""

[[workspace]]
title = "Web"
icon = ""

[[workspace]]
title = "Code"
icon = ""

[[workspace]]
title = "Ops"
icon = ""

[[workspace]]
title = "Dotfiles"
icon = ""

[[workspace]]
title = "Comms"
icon = ""

[[workspace]]
title = "Cookies"
icon = ""

[tile_template."top-left-50"]
width = 40
height = 50
horizontal_anchor = "left"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = -30

[tile_template."right-half"]
width = 50
height = 100
horizontal_anchor = "right"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = -10

[tile_template."left-half"]
width = 50
height = 100
horizontal_anchor = "left"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = -20

[tile_template."right-70"]
width = 70
height = 100
horizontal_anchor = "right"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = 10

[tile_template."left-70"]
width = 70
height = 100
horizontal_anchor = "left"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = 0

[tile_template."quarter-top-left"]
width = 50
height = 50
horizontal_anchor = "left"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = 20

[tile_template."quarter-top-right"]
width = 50
height = 50
horizontal_anchor = "right"
horizontal_position = 0
vertical_anchor = "top"
vertical_position = 0
weight = 30

[tile_template."quarter-bottom-left"]
width = 50
height = 50
horizontal_anchor = "left"
horizontal_position = 0
vertical_anchor = "bottom"
vertical_position = 0
weight = 40

[tile_template."quarter-bottom-right"]
width = 50
height = 50
horizontal_anchor = "right"
horizontal_position = 0
vertical_anchor = "bottom"
vertical_position = 0
weight = 50
