include-directory = configs

[bar/top]
background = ${colours.background}
foreground = ${colours.foreground}

font-0 = "Verb Light:antialias=false:pixelsize=12;1"
# file:///home/patrick/.fonts/Lucide/unicode.html
font-1 = "lucide:pixelsize=12;2"
font-2 = "VerbExCond Light:antialias=false:pixelsize=12;1"
# https://www.nerdfonts.com/cheat-sheet
font-3 = "Symbols Nerd Font Mono:pixelsize=12;2"
# https://fontawesome.com/icons
font-4 = "Font Awesome 7 Brands:style=Regular:pixelsize=12;2"
font-5 = "Verb Light:weight=300:antialias=false:pixelsize=12;1"

height = 30
width = 100%
line-size = 1
enable-ipc = false

wm-name = polybar-top

modules-left = powermenu msgvault issues github
modules-center = date
modules-right = telegram signal tray

spacing = 0
module-margin = 0
