[fonts]
; Fonts documentation:      https://github.com/polybar/polybar/wiki/Fonts
; finding fonts:           `fc-list | grep "Font Name"`
; debug font use:          `FC_DEBUG=1 polybar mybar ...`
; matching selected fonts: `fc-match "VerbExCond:style=Light"`
; cleanup font cache:      `fc-cache -frv`
; Nerd Fonts:               NerdFontsSymbolsOnly.zip from release page
; Usage:                   `%{T3}Inactive%{T-} %time%` 1-based index of font in config
;
; final font setup (automatic with fallbacks)
; text = Verb Light, or explicitly VerbExCond Light `%{T1}Verb Ex Cond Formatted Text%{T-}`
; icons = Lucide, or Nerd Font Mono, or Font Awesome Brands
text = "Verb:style=Light:size=9;1"
text-condensed = "VerbExCond:style=Light:size=9;1"
; file:///home/patrick/.fonts/System/lucide/unicode.html
icons-lucide = "lucide:style=Regular:size=10;2"
; https://www.nerdfonts.com/cheat-sheet
icons-nerd = "Symbols Nerd Font Mono:style=Regular:size=10;2"
; https://fontawesome.com/search?ip=brands
icons-brands = "Font Awesome 7 Brands:style=Regular:style=Regular:size=10;2"
