[bar/base]

background = ${colours.background}
foreground = ${colours.foreground}

font-0 = "Verb Light:antialias=false:pixelsize=12;1"
# file:///home/patrick/.fonts/Lucide/unicode.html
font-1 = "lucide:pixelsize=12;2"
font-2 = "VerbExCond Light:antialias=false:pixelsize=12;1"
# https://www.nerdfonts.com/cheat-sheet
font-3 = "Symbols Nerd Font Mono:pixelsize=12;2"

height = 40
width = 100%
line-size = 1
enable-ipc = true
