[module/github]
type = internal/github

; Accessing an access token stored in an environment variable
; @todo fix Github token management
token = ${env:GITHUB_TOKEN_FULL_DEV}

; The github user for the token
user = davidsneighbour

; Whether empty notifications should be displayed or not
empty-notifications = false

; Number of seconds in between requests
interval = 60

; Github API URL
api-url = https://api.github.com/

; Available tags:
;   <label> (default)
#format =  <label>
format = %{A1:xdg-open https\://github.com/notifications:} <label>%{A}

; Available tokens:
;   %notifications% (default)
; Default: Notifications: %notifications%
label = %notifications%

; Used when GitHub can't be reached
; Available tags:
;   <label-offline> (default)
format-offline = <label-offline>

; Available tokens:
;   None
; Default: Offline
label-offline = 
