[module/ewmh]
type = internal/xworkspaces
; @see https://github.com/polybar/polybar/wiki/Module:-xworkspaces

; Reverse the scroll direction
; Default: false
; New in version 3.6.0
reverse-scroll = true

; icon-[0-9]+ = <desktop-name>;<icon>
; Map desktop names to some icon. The icon is then available in the %icon% token
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktop names using:
; $ xprop -root _NET_DESKTOP_NAMES
; NOTE: Neither <desktop-name> nor <icon> can contain a semicolon (;)
; file:///home/patrick/.fonts/System/lucide/unicode.html
# Read docs/workspaces.md for details on how to configure workspaces and tile templates.
icon-0 = Dashboard;
icon-1 = Web;
icon-2 = Code;
icon-3 = Ops;
icon-4 = Notes;
icon-5 = Bots;
icon-6 = Dotfiles;
icon-7 = Comms;
icon-8 = Cookies;

; an under construction icon
icon-default = 

; Used for the currently selected workspaces
; Available tokens: %name%, %icon%, %index%, %nwin%
label-active = %icon% %name%
label-active-foreground = ${colours.green}
label-active-background = ${colours.selection}
label-active-underline = ${colours.purple}
label-active-padding = 4

; Used for workspaces at least one window
; Available tokens: %name%, %icon%, %index%, %nwin%
label-occupied = %icon%
label-occupied-padding = 4
label-occupied-foreground = ${colours.orange}
label-occupied-underline = ${colours.primary}

; Used for workspaces containing a window that is demanding attention (has the
; urgent bit set)
; Available tokens: %name%, %icon%, %index%, %nwin%
label-urgent = %icon%
label-urgent-foreground = ${colours.background}
label-urgent-background = ${colours.pink}
label-urgent-underline = ${colours.orange}
label-urgent-padding = 4

; Used for workspaces without windows
; Available tokens: %name%, %icon%, %index%, %nwin%
label-empty = %icon%
label-empty-foreground = ${colours.selection}
label-empty-underline = ${colours.selection}
label-empty-padding = 4
