[module/powermenu]
# https://github.com/polybar/polybar/wiki/Module:-menu
type = custom/menu

expand-right = true
format-background = ${colours.selection}
format-padding = 4

label-open = 
label-open-padding = 0
label-close = 
label-close-padding-right = 4
label-close-foreground = ${colours.red}

menu-0-0 = reboot
menu-0-0-exec = #powermenu.open.1
menu-0-0-background = ${colours.selection}
menu-0-0-padding = 4
menu-0-1 = power off
menu-0-1-exec = #powermenu.open.2
menu-0-1-background = ${colours.selection}
menu-0-1-padding = 4

menu-1-0 = back
menu-1-0-exec = #powermenu.open.0
menu-1-0-background = ${colours.red}
menu-1-0-foreground = ${colours.selection}
menu-1-0-padding = 4
menu-1-1 = reboot
menu-1-1-exec = shutdown now -r
menu-1-1-background = ${colours.red}
menu-1-1-foreground = ${colours.selection}
menu-1-1-padding = 4

menu-2-0 = power off
menu-2-0-exec = shutdown now -h
menu-2-0-background = ${colours.red}
menu-2-0-foreground = ${colours.selection}
menu-2-0-padding = 4
menu-2-1 = back
menu-2-1-exec = #powermenu.open.0
menu-2-1-background = ${colours.red}
menu-2-1-foreground = ${colours.selection}
menu-2-1-padding = 4
