[module/telegram]
type = custom/script
interval = 1
label-padding = 4
exec = ~/.config/polybar/scripts/window-colour.sh --config "/home/patrick/.config/polybar/configs/01-settings.ini" --wmclass "Telegram.TelegramDesktop" --label "󰬁" --section "colours" --hidden-key "foreground" --shown-key "selection"
click-left = ~/.config/polybar/scripts/toggle-window.sh --wmclass "Telegram.TelegramDesktop"

# wmctrl -lx | grep -i telegram
