[module/signal]
type = custom/script
interval = 1
label-padding = 4
exec = ~/.config/polybar/scripts/window-colour.sh --config "/home/patrick/.config/polybar/configs/01-settings.ini" --wmclass "signal.Signal" --label "󰬀" --section "colours" --hidden-key "foreground" --shown-key "selection"
click-left = ~/.config/polybar/scripts/toggle-window.sh --wmclass "signal.Signal"

# wmctrl -lx | grep -i telegram
