---
services:
  openpencil:
    # secretlint-disable-next-line @secretlint/secretlint-rule-secp256k1-privatekey
    image: ghcr.io/zseven-w/openpencil-web:v0.8.2@sha256:e13982f18ba3f87ef422c84738be261a337ceccd877aff6ea69a16354fce9775
    container_name: openpencil
    restart: unless-stopped

    ports:
      - "3020:3100"

    environment:
      OPENPENCIL_SERVE_PORT: "3100"
