---
services:
  openpencil:
    # secretlint-disable-next-line @secretlint/secretlint-rule-secp256k1-privatekey
    image: ghcr.io/zseven-w/openpencil-web:v0.8.1@sha256:80eb447edc616a6d2f40f4ebf8fa23baecd044db46f7bf5d5d121eb533345c70
    container_name: openpencil
    restart: unless-stopped

    ports:
      - "3020:3100"

    environment:
      OPENPENCIL_SERVE_PORT: "3100"
