import { randomUUID } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { DatabaseSync } from "node:sqlite";

const marker =
  "<!-- Generated by git-collection. Disposable; regenerate from SQLite. -->";
const filePattern =
  /^(daily\/\d{4}-\d{2}-\d{2}|weekly\/\d{4}-W\d{2}|monthly\/\d{4}-\d{2}|repositories\/[a-f0-9-]{36})\.md$/;

function markdown(value: unknown): string {
  return String(value)
    .replace(/\p{Cc}/gu, " ")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/([\\`*_\[\]|])/g, "\\$1");
}

function rejectSymlinks(path: string): void {
  let current = resolve(path);
  while (dirname(current) !== current) {
    if (existsSync(current) && lstatSync(current).isSymbolicLink())
      throw new Error(`Report destination contains a symlink: ${current}`);
    current = dirname(current);
  }
}

function atomicWrite(path: string, text: string): void {
  const temporary = `${path}.${randomUUID()}.partial`;
  try {
    writeFileSync(temporary, text, { flag: "wx", mode: 0o600 });
    renameSync(temporary, path);
  } finally {
    if (existsSync(temporary)) unlinkSync(temporary);
  }
}

export function generateReports(
  db: DatabaseSync,
  output: string,
): { files: number; removed: number } {
  const root = resolve(output);
  rejectSymlinks(root);
  const generated = new Map<string, string>();
  db.exec("BEGIN");
  try {
    const dimensions = [
      { folder: "daily", expression: "activity_date" },
      {
        folder: "weekly",
        expression: "strftime('%G-W%V', committer_date, '+7 hours')",
      },
      { folder: "monthly", expression: "activity_month" },
      { folder: "repositories", expression: "repository_id" },
    ];
    for (const dimension of dimensions) {
      const groups = db
        .prepare(`SELECT ${dimension.expression} AS label, count(*) AS commits,
        count(DISTINCT repository_id) AS repositories, count(DISTINCT author_email) AS authors
        FROM v_commits GROUP BY ${dimension.expression} ORDER BY label`)
        .all();
      const examplesByGroup = new Map<
        string,
        { repository: unknown; hash: unknown; subject: unknown }[]
      >();
      const recent = db.prepare(`SELECT label, repository, hash, subject FROM (
        SELECT ${dimension.expression} AS label, repository, hash, subject,
        row_number() OVER (PARTITION BY ${dimension.expression}
          ORDER BY unixepoch(committer_date) DESC, hash) AS position
        FROM v_commits
      ) WHERE position <= 20 ORDER BY label, position`);
      for (const commit of recent.iterate()) {
        const label = String(commit.label);
        const examples = examplesByGroup.get(label) ?? [];
        examples.push({
          repository: commit.repository,
          hash: commit.hash,
          subject: commit.subject,
        });
        examplesByGroup.set(label, examples);
      }
      for (const group of groups) {
        const filename = `${dimension.folder}/${String(group.label)}.md`;
        if (!filePattern.test(filename))
          throw new Error(
            "Invalid report date or repository ID. Check catalogue metadata.",
          );
        const examples = examplesByGroup.get(String(group.label)) ?? [];
        const title =
          dimension.folder === "repositories"
            ? (examples[0]?.repository ?? group.label)
            : group.label;
        const lines = [
          marker,
          `# ${markdown(title)}`,
          "",
          `Commits: ${group.commits}. Repositories: ${group.repositories}. Authors: ${group.authors}.`,
          "",
          "Activity dates use Asia/Bangkok. Counts include separate clones and retained rewritten history.",
          "",
          "## Recent commits",
          "",
          ...examples.map(
            (commit) =>
              `* ${markdown(commit.repository)}: ${markdown(commit.subject)} (\`${String(commit.hash).slice(0, 12)}\`)`,
          ),
          "",
        ];
        generated.set(filename, lines.join("\n"));
      }
    }
    db.exec("COMMIT");
  } catch (error) {
    db.exec("ROLLBACK");
    throw error;
  }
  const manifest = join(root, "generated-files.json");
  rejectSymlinks(manifest);
  const previous: unknown = existsSync(manifest)
    ? JSON.parse(readFileSync(manifest, "utf8"))
    : [];
  if (
    !Array.isArray(previous) ||
    !previous.every(
      (file: unknown) => typeof file === "string" && filePattern.test(file),
    )
  ) {
    throw new Error(
      "Invalid generated report manifest. Restore it or choose a new output directory.",
    );
  }
  const oldFiles = previous as string[];
  for (const filename of new Set([...oldFiles, ...generated.keys()])) {
    const path = join(root, filename);
    rejectSymlinks(path);
    if (existsSync(path) && !readFileSync(path, "utf8").startsWith(marker)) {
      throw new Error(
        `Refusing to replace or remove an unrecognised report: ${path}`,
      );
    }
  }
  mkdirSync(root, { recursive: true, mode: 0o700 });
  for (const [filename, content] of generated) {
    const path = join(root, filename);
    mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
    atomicWrite(path, content);
  }
  let removed = 0;
  for (const filename of oldFiles) {
    const path = join(root, filename);
    if (!generated.has(filename) && existsSync(path)) {
      unlinkSync(path);
      removed++;
    }
  }
  atomicWrite(manifest, JSON.stringify([...generated.keys()], null, 2) + "\n");
  return { files: generated.size, removed };
}
