################################################################################
# Setup configuration for the protected repository
################################################################################
- link:
    ~/.env: protected/.env
