################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- shell:
    - ["mkdir -p ~/.config", "creating config folder (if it doesn't exist yet)"]

- link:
    ############################################################################
    # file links
    ############################################################################
    ~/.bash_logout: home/.bash_logout
    ~/.bash_profile: home/.bash_profile
    ~/.bashrc: home/.bashrc
    ##################################################################
    # directory links
    ##################################################################
    ~/snap/joplin-desktop/current/.config/joplin-desktop/plugins: filesystem/snap/joplin-desktop/current/.config/joplin-desktop/plugins
    ~/snap/joplin-desktop/current/.config/joplin-desktop/settings.json: filesystem/snap/joplin-desktop/current/.config/joplin-desktop/settings.json
    ############################################################################
    # protected links default files
    ############################################################################
    ~/.env: filesystem/.env
