---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- plugins:
    - dotbot-plugins/crontab-dotbot/
    # - dotbot-plugins/dotbot-aptget/
    
- defaults:
      link:
          create: true
          relink: true
          force: true

- clean: ["~"]

- link:
      ############################################################################
      # file links
      ############################################################################
      ~/.barriers.conf: filesystem/.barriers.conf
      ~/.bash_logout: filesystem/.bash_logout
      ~/.bash_profile: filesystem/.bash_profile
      ~/.bashrc: filesystem/.bashrc
      #~/.better-commits.json: filesystem/.better-commits.json
      ~/.cargo/.crates.toml: filesystem/.cargo/.crates.toml
      ~/.cargo/env: filesystem/.cargo/env
      ~/.config/starship.toml: filesystem/.config/starship.toml
      ~/.config/user-dirs.dirs: filesystem/.config/user-dirs.dirs
      ~/.czrc: filesystem/.czrc
      ~/.dir_colors: filesystem/.dir_colors
      ~/.face.icon: filesystem/.face.icon
      ~/.editorconfig: filesystem/.editorconfig
      ~/.fehbg: filesystem/.fehbg
      ~/.fixpackrc: filesystem/.fixpackrc
      ~/.gitmessage: filesystem/.gitmessage
      ~/.gitconfig: filesystem/.gitconfig
      ~/.gitignore: filesystem/.gitignore.template
      ~/.git-templates: filesystem/.git-templates
      ~/.hidden: filesystem/.hidden
      ~/.nvmrc: filesystem/.nvmrc
      ~/.pam_environment: filesystem/.pam_environment
      ~/.profile: filesystem/.profile
      ~/.remarkrc.js: filesystem/.remarkrc.js
      ~/.remarkignore: filesystem/.remarkignore
      ~/.Xresources: filesystem/.Xresources
      ~/.nvm/default-packages: filesystem/.nvm/default-packages
      ##################################################################
      # directory links
      ##################################################################
      ~/.config/autostart: filesystem/.config/autostart
      ~/.config/assets: filesystem/.themes/Dracula/assets
      ~/.config/BetterDiscord: filesystem/.config/BetterDiscord
      ~/.config/fastfetch: filesystem/.config/fastfetch
      ~/.config/filezilla: filesystem/.config/filezilla
      ~/.config/fontconfig: filesystem/.config/fontconfig
      ~/.config/gh: filesystem/.config/gh
      ~/.config/gtk-3.0: filesystem/.config/gtk-3.0
      ~/.config/gtk-4.0: filesystem/.config/gtk-4.0
      ~/.config/i3: filesystem/.config/i3
      ~/.config/inkscape: filesystem/.config/inkscape
      ~/.config/lsd: filesystem/.config/lsd
      ~/.config/jrnl: filesystem/.config/jrnl
      ~/.config/neofetch: filesystem/.config/neofetch
      ~/.config/polybar: filesystem/.config/polybar
      ~/.config/qt5ct: filesystem/.config/qt5ct
      ~/.config/rofi: filesystem/.config/rofi
      ~/.config/sublime-merge: filesystem/.config/sublime-merge
      ~/.config/sublime-text: filesystem/.config/sublime-text
      ~/.config/tabtab: filesystem/.config/tabtab
      ~/.config/wlogout: filesystem/.config/wlogout
      ~/.gnome: filesystem/.gnome
      ~/.icons: filesystem/.icons
      ~/.logs: logs
      ~/.themes: filesystem/.themes
      ~/.vim: filesystem/.vim

      # background images for Cinnamon
      ~/.config/cinnamon/backgrounds/user-folders.lst: configs/wallpapers/user-folders.lst
      ~/.config/cinnamon/backgrounds/black-and-white: configs/wallpapers/black-and-white
      ~/.config/cinnamon/backgrounds/botanics: configs/wallpapers/botanics
      ~/.config/cinnamon/backgrounds/colors: configs/wallpapers/colors
      ~/.config/cinnamon/backgrounds/graphic: configs/wallpapers/graphic
      ~/.config/cinnamon/backgrounds/liminal: configs/wallpapers/liminal
      ~/.config/cinnamon/backgrounds/synched: configs/wallpapers/synched

# - shell:
#       # - 'gsettings set org.gnome.desktop.interface gtk-theme "Dracula"'
#       # - 'gsettings set org.gnome.desktop.wm.preferences theme "Dracula"'
# #    - "gsettings set org.gnome.desktop.interface icon-theme \"Dracula\""

- crontab:
      - cron: 0 0 * * *
        command: ${HOME}/github.com/davidsneighbour/dotfiles/bashrc/helpers/update-npm.sh >> ${HOME}/.logs/cron.log 2>&1
      - cron: 30 */4 * * *
        command: ${HOME}/github.com/davidsneighbour/dotfiles/bashrc/helpers/filespace-discord.sh >> ${HOME}/.logs/cron.log 2>&1
      # - cron: 0 18 * * *
      #   command: /bin/bash -c "cd ${HOME}/github.com/davidsneighbour/dotfiles && keybindingsmanager -e etc/keycombinations.csv" >> ${HOME}/.logs/cron.log 2>&1
      - cron: 55 * * * *
        command: /home/patrick/github.com/davidsneighbour/dotfiles/bashrc/helpers/keycombinations.sh
      - cron: 0 6,12,18 * * *
        command: ${HOME}/github.com/davidsneighbour/lighthousing/cronjob.sh >> ${HOME}/.logs/cron.log 2>&1
      - cron: "@reboot"
        command: ${HOME}/github.com/davidsneighbour/lighthousing/cronjob.sh >> ${HOME}/.logs/cron.log 2>&1
