---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- plugins:
    - dotbot-plugins/crontab-dotbot/
    - dotbot-plugins/dotbot-aptget/
    
- defaults:
    link:
      create: true
      relink: true
      force: true

- aptget:
    xclip:
    dnsmasq-base:
    gzip:
    ubuntu-drivers-common:
    git:
    terminator:
    ca-certificates:
    curl:
    flatpak:
        ppa_source: ppa:flatpak/stable
        upgrade: true
