# see https://github.com/anishathalye/dotbot
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- shell:
    - ["mkdir -p ~/.config", "creating config folder (if it doesn't exist yet)"]
#    - [git submodule update --init --recursive, Installing submodules]
#    - [bin/setup-system, Installing required tools and IDEs]
#- sudo snap install --classic code
#- sudo snap install todoist
#####################################################################################
    #- sudo apt purge libreoffice
    - sudo ./bin/setup-system.sh
#- sudo snap install android-studio
#- sudo snap install authy
#- sudo snap install bitcoin-core
#- sudo snap install chromium
#- sudo snap install flutter
#- sudo snap install go
#- sudo snap install libreoffice
#- sudo snap install phpstorm
#- sudo snap install ruby
#- sudo snap install slack
#- sudo snap install deno

- link:
    ##################################################################
    # file links
    ##################################################################
    ~/.bash_logout: home/.bash_logout
    ~/.bash_profile: home/.bash_profile
    ~/.bashrc: home/.bashrc
    ~/.colordiff: home/.colordiff
    ~/.dmrc: home/.dmrc
    ~/.editorconfig: home/.editorconfig
    ~/.env: .env
    ~/.face.icon: home/.face.icon
    ~/.fehbg: home/.fehbg
    ~/.fixpackrc: home/.fixpackrc
    ~/.gitconfig: home/.gitconfig
    ~/.gitignore: home/.gitignore.template
    ~/.git-template: home/.git-template
    ~/.guake-indicator: home/.guake-indicator
    ~/.gtk-bookmarks: home/.gtk-bookmarks
    ~/.gtkrc-2.0.mine: home/.gtkrc-2.0.mine
    ~/.hidden: home/.hidden
    ~/.inputrc: home/.inputrc
    ~/.npmrc: .npmrc
    ~/.pam_environment: home/.pam_environment
    ~/.remarkignore: home/.remarkignore
    ~/.remarkrc.js: home/.remarkrc.js
    ~/.selected_editor: home/.selected_editor
    ~/.textlintrc.js: home/.textlintrc.js
    ~/.vimrc: home/.vimrc
    ~/.vuerc: home/.vuerc
    ~/.xinputrc: home/.xinputrc
    ~/.Xresources: home/.Xresources
    ~/.xscreensaver: home/.xscreensaver
    ##################################################################
    # directory links
    ##################################################################
    ~/.dotfiles: ""
    ~/.conky: home/.conky
    ~/.cargo: home/.cargo
    ~/.fonts: home/.fonts
    ~/.config/autostart: home/.config/autostart
    ~/.config/Code: home/.config/Code
    ~/.config/dunst: home/.config/dunst
    ~/.config/filezilla: home/.config/filezilla
    ~/.config/i3: home/.config/i3
    ~/.config/jrnl: home/.config/jrnl
    ~/.config/neofetch: home/.config/neofetch
    ~/.config/polybar: home/.config/polybar
    ~/.config/rofi: home/.config/rofi
    ~/.config/sublime-text-3: home/.config/sublime-text-3
    ~/.config/tabtab: home/.config/tabtab
    ~/.local/share/applications: home/.local/share/applications
    ~/.shutter: home/.shutter
    ~/.ssh: home/.ssh
    ~/.themes: home/.themes
    ~/.icons: home/.icons
    ~/.wallpaper.jpg: home/wallpapers/wallpaper-002.jpg
# - shell:
#     - bash ./home/.config/Code/extensions.sh
#     - npm install -g npm-check-updates
#     - cargo install git-cliff
