---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- link:
    # autostart
    configs/system/autostart/donald/conky.desktop: configs/system/autostart/available/conky.desktop
    configs/system/autostart/donald/Enpass.desktop: configs/system/autostart/available/Enpass.desktop
    configs/system/autostart/donald/shutter.desktop: configs/system/autostart/available/shutter.desktop
