# see https://github.com/anishathalye/dotbot
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- shell:
    - ["mkdir -p ~/.config", "creating config folder (if it doesn't exist yet)"]
    - [bin/setup-system, Installing required tools and IDEs]
    - sudo snap install --classic code
    - sudo snap install todoist
    - sudo ./bin/setup-system.sh
    - sudo snap install android-studio
    - sudo snap install authy
    - sudo snap install bitcoin-core
    - sudo snap install chromium
    - sudo snap install flutter
    - sudo snap install go
    - sudo apt purge libreoffice
    - sudo snap install libreoffice
    - sudo snap install phpstorm
    - sudo snap install ruby
    - sudo snap install slack
    - sudo snap install deno
