################################################################################
# New setup configuration for dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################

