################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- shell:
    - "rm -f ~/.bash_history ~/.lesshst ~/.viminfo ~/.sudo_as_admin_successful"
    - "rm -f ~/.wget-hsts ~/.ncu-cache.json ~/.lesshst"
    - "rm -f ~/hs_err_pid*.log"
