---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- shell:
    - rm -f ~/.bash_history
    - rm -f ~/.lesshst
    - rm -f ~/.ncu-cache.json
    - rm -f ~/.sudo_as_admin_successful
    - rm -f ~/.viminfo
    - rm -f ~/.wget-hsts
    - rm -f ~/hs_err_pid*.log
    - sudo apt autoremove --yes
    - sudo apt clean --yes
