---
################################################################################
# Setup configuration for the protected repository
################################################################################
- plugins:
    - dotbot-plugins/crontab-dotbot/
    - dotbot-plugins/dotbot-aptget/

- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- link:
    ~/.env: protected/.env
    ~/.gmailctl: protected/.gmailctl
    ~/.gnupg: protected/.gnupg
    ~/.npmrc: protected/.npmrc
    ~/.sentryclirc: protected/.sentryclirc
    ~/.fonts: protected/.fonts
    ~/.ssh: protected/.ssh
    ~/JoplinBackup: protected/JoplinBackup
    ~/.config/Cryptomator: protected/Cryptomator
    ~/.config/transmission: protected/transmission
    ~/.config/filezilla/filezilla.xml: protected/filezilla/filezilla.xml
    ~/.config/filezilla/sitemanager.xml: protected/filezilla/sitemanager.xml
    ~/.config/filezilla/trustedcerts.xml: protected/filezilla/trustedcerts.xml
    # docker containers with sensitive data
    containers/homepage/config: protected/containers/homepage/config
    containers/paperless/db: protected/containers/paperless/db
