---
extends: existence
message: "'%s' is putting undue emphasis on symbolism and importance."
ignorecase: true
level: warning
tokens:
  - Industry reports
  - Observers have cited
  - Some critics argue
