#!/bin/bash
# shellcheck disable=all

A collection of several useful generators.

Usage:
  hugo gen [command]

Available Commands:
  chromastyles Generate CSS stylesheet for the Chroma code highlighter
  doc          Generate Markdown documentation for the Hugo CLI.
  man          Generate man pages for the Hugo CLI

Flags:
  -h, --help   help for gen

Global Flags:
      --config string              config file (default is path/config.yaml|json|toml)
      --configDir string           config dir (default "config")
      --debug                      debug output
  -e, --environment string         build environment
      --ignoreVendorPaths string   ignores any _vendor for module paths matching the given Glob pattern
      --log                        enable Logging
      --logFile string             log File path (if set, logging enabled automatically)
      --quiet                      build in quiet mode
  -s, --source string              filesystem path to read files relative from
      --themesDir string           filesystem path to themes directory
  -v, --verbose                    verbose output
      --verboseLog                 verbose logging

Use "hugo gen [command] --help" for more information about a command.
