section: screens
	dionysus:
		# set to true is caps lock is a switch and not a button
		halfDuplexCapsLock = false
		# set to true is num lock is a switch and not a button
		halfDuplexNumLock = false
		# set to true is scroll lock is a switch and not a button
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none 
		switchCornerSize = 0
	locutus:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none 
		switchCornerSize = 0
end

section: aliases
end

section: links
	dionysus:
		right = locutus
	locutus:
		left = dionysus
end

section: options
	relativeMouseMoves = false
	screenSaverSync = true
	win32KeepForeground = false
	clipboardSharing = true
	switchCorners = none 
	switchCornerSize = 0
end

