---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################
- description: Main workstation dotfiles setup (links, tools, cronjobs, and host-specific configs).

- plugins:
    - modules/dotbot-plugins/crontab-dotbot/

- link:
    ~/github.com/davidsneighbour/dotfiles/containers/hal2025/paperless/consume: /mnt/storage/Paperless/consume
    
- crontab:
    - cron: 0 */2 * * *
      command: ${HOME}/github.com/davidsneighbour/dotfiles/containers/hal2025/paperless/backup

    - cron: "15 15 * * *"
      comment: "daily docker container backup"
      command: ${HOME}/.dotfiles/bashrc/cronjobs/docker-backup.sh --apply  --docker-path ${HOME}/.dotfiles/containers/hal2025  --backup-path /mnt/storage/Backup/Docker/HAL2025  --verbose  >> "${HOME}/.logs/cron/docker-backup.log" 2>&1
        
    - cron: "20 15 * * 0"
      comment: "weekly docker container backup to keep"
      command: ${HOME}/.dotfiles/bashrc/cronjobs/docker-backup.sh --keep --apply --docker-path ${HOME}/.dotfiles/containers/hal2025 --backup-path /mnt/storage/Backup/Docker/HAL2025 --keep-count 10 --verbose >> "${HOME}/.logs/cron/docker-backup.log" 2>&1