---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
#
# @description Main workstation dotfiles setup (links, tools, cronjobs, and host-specific configs).
#
################################################################################

- defaults:
    link:
      create: true
      relink: true
      force: true

- create:
    logs:
      mode: 0777

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ~/.dotfiles: ""
    ~/.logs: logs

    # bashrc setup
    ~/.bash_logout: bashrc/.bash_logout
    ~/.bash_profile: bashrc/.bash_profile
    ~/.bashrc: bashrc/.bashrc
    ~/.profile: bashrc/.profile
    ~/.config/starship.toml: configs/system/starship/starship.toml
    ~/.config/atuin: configs/system/atuin

    # xfwm setup
    ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml: configs/system/xfce/xfce4-keyboard-shortcuts.xml
    ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml: configs/system/xfce/xfwm4.xml

    # workspaces setup
    ~/github.com/davidsneighbour/gmailctl-config: modules/gmailctl
    ~/github.com/davidsneighbour/dotfiles-protected: modules/protected

    # system setup
    ~/.face.icon: configs/system/face.icon
    ~/.face: configs/system/face.icon
    ~/.config/conky: configs/system/conky
    ~/.config/user-dirs.dirs: configs/system/user-dirs.dirs
    ~/.config/polybar: configs/system/polybar
    ~/.config/i3: configs/system/i3
    ~/.logs: logs
    ~/.nvmrc: .nvmrc
    ~/.editorconfig: .editorconfig
    ~/.fixpackrc: .fixpackrc
    ~/.hidden: configs/system/.hidden
    ~/.pam_environment: configs/system/.pam_environment
    ~/.czrc: configs/system/.czrc
    ~/.config/sublime-merge: configs/system/sublime-merge
    ~/.config/sublime-text: configs/system/sublime-text
    ~/.config/filezilla: configs/system/filezilla
    ~/.config/rofi: configs/system/rofi
    ~/.barrier-server.config: configs/system/barrier/barrier-server.conf

    # autostart
    ~/.config/autostart: configs/system/autostart/${HOSTNAME}

    # git setup
    ~/.gitignore: configs/system/git/global.gitignore
    ~/.gitmessage: configs/system/git/.gitmessage
    ~/.gitconfig: configs/system/git/.gitconfig
    ~/.git-templates: configs/system/git/.git-templates

    # folders in ~/.local/share
    ~/.local/share/applications: configs/system/launchers

    # theme configs
    ~/.icons/DNB-Bibata: configs/theme/DNB-Bibata
    ~/.icons/DNB: configs/theme/DNB

    # Tool configs
    ~/.config/fastfetch: configs/system/fastfetch
    ~/.local/share/vale: configs/system/vale
    ~/.config/vale: configs/system/vale
    ~/.config/github-label-manager: configs/system/git/github-label-manager

    # node configs
    ~/.ncurc.js: configs/system/npm/ncu.cjs
    ~/.nvm/default-packages: configs/system/npm/default-packages

    # qbittorrent
    ~/.config/qBittorrent/watched_folders.json: configs/system/bittorrent/qbittorrent-watched_folders.json
    ~/.config/qBittorrent/qBittorrent.con: configs/system/bittorrent/qbittorrent.conf
    ~/.config/qBittorrent/categories.json: configs/system/bittorrent/qbittorrent-categories.json

    # content quality
    ~/.remarkrc.js: configs/content/.remarkrc.js
    ~/.remarkignore: configs/content/.remarkignore

    # fonts
    ~/.fonts: configs/fonts

    # fixing emojis in chrome tab names (I know, right?)
    ~/.config/fontconfig/conf.d/01-emoji.conf: configs/system/fontconfig/01-emoji.conf

- shell:
    - description: "\e[1;38;5;103mCreate logs directory if it doesn't exist:\e[0m\e[1;38;5;66m"
      command: |
        if [ ! -d "$HOME/.dotfiles/logs" ]; then
          mkdir -p "$HOME/.dotfiles/logs"
        fi
        if [[ -L "$HOME/.logs" ]]; then
          ln -sfn $HOME/.dotfiles/logs $HOME/.logs
        elif [[ ! -e "$HOME/.logs" ]]; then
          ln -s $HOME/.dotfiles/logs $HOME/.logs
        else
          echo "[ERROR] Exists and is not a symlink: $HOME/.logs"
        fi
      quiet: true
      stdin: false   # Allow a command to read from standard input (default: false)
      stdout: false  # Show a command's output from stdout (default: false)
      stderr: false  # Show a command's output from stderr (default: false)

    #     # create autostart folder connection
    #     - ln -f -s ${HOME}/.dotfiles/configs/system/autostart/${HOSTNAME} ${HOME}/.config/autostart
    - description: "\e[1;38;5;103mSymlinking mounts:\e[0m\e[1;38;5;66m"
      command: |
        if [[ "$(hostname)" == "locutus" ]]; then
          if [[ -L "$HOME/Downloads/Paperless" ]]; then
            ln -sfn /mnt/storage/Paperless/consume $HOME/Downloads/Paperless
          elif [[ ! -e "$HOME/Downloads/Paperless" ]]; then
            ln -s /mnt/storage/Paperless/consume $HOME/Downloads/Paperless
          else
            echo "[ERROR] Exists and is not a symlink: $HOME/Downloads/Paperless"
          fi
        fi
      quiet: true
