#!/bin/bash
# shellcheck shell=bash
# Bashrc partial (sourced by ~/.bashrc)

# load the bashrc helper functions
# shellcheck disable=SC2154 # defined in bashrc
dnb_auto_source "${BASHRC_PATH}"/partials/_topical/*.bash
