#!/bin/bash

function code() {
  local binary="/usr/bin/code"
  if [ $# -eq 0 ]; then
    folder="$(pwd)"
  else
    target="$1"
    if [ -f "$target" ]; then
      if [[ "$target" == *.code-workspace ]]; then
        $binary "$target"
        return
      else
        folder=$(dirname "$target")
      fi
    elif [ -d "$target" ]; then
      folder="$target"
    else
      echo "Invalid file or directory: $target"
      return 1
    fi
  fi
  workspace_file=$(find "$folder" -maxdepth 1 -type f -name "*.code-workspace" | head -n 1)
  if [ -n "$workspace_file" ]; then
    $binary "$workspace_file"
    if [ -f "$target" ]; then
      $binary "$target"
    fi
  else
    $binary "$folder"
  fi
}
