#!/bin/bash
# shellcheck disable=SC2032
function git() {
  if [[ $# -eq 0 ]]; then
    command git
    return
  fi

  FILE=.git/hooks/status
  case "$1" in
  status)
    [[ -x $FILE ]] && bash $FILE
    command git "$@"
    ;;
  stash)
    if [[ $# -eq 1 || ("$2" == "-m" && $# -ge 3) ]]; then
      # Prepare arguments for git stash command
      local stash_args=()
      if [[ "$2" == "-m" ]]; then
        # Include -m and the message if provided
        stash_args=("--include-untracked" "$2" "$3")
        # Capture any additional message parts if present
        for ((i = 4; i <= $#; i++)); do
          stash_args+=("${!i}")
        done
      else
        stash_args=("--include-untracked")
      fi

      # Attempt to stash changes and capture the output
      output=$(command git stash "${stash_args[@]}" 2>&1)
      echo "$output"
      if echo "$output" | grep -q "No local changes to save"; then
        echo -e "\nCurrent stashes"
        command git stash list
      fi
    else
      command git "$@"
    fi
    ;;
  *)
    command git "$@"
    ;;
  esac
}
