#!/bin/bash


# for repo in $repos; do (g_repo_transfer "$repo" "$1" "$2"); done
function g_repo_transfer() {
  curl -vL \
    -u "$2:${GITHUB_SECRET}" \
    -H "Content-Type: application/json" \
    -H "Accept: application/vnd.github.v3+json" \
    -X POST https://api.github.com/repos/"$2"/"$1"/transfer \
    -d '{"new_owner":"'"$3"'"}' |
    jq .
}
