#!/bin/bash

function roll() {
  if [ "$#" -ne 0 ]; then
    FILE="$1"
    case "${FILE}" in
    *.tar.bz2 | *.tbz2) shift && tar cvjf "${FILE}" "$*" ;;
    *.tar.gz | *.tgz) shift && tar cvzf "${FILE}" "$*" ;;
    *.tar) shift && tar cvf "${FILE}" "$*" ;;
    *.zip) shift && zip "${FILE}" "$*" ;;
    *.rar) shift && rar "${FILE}" "$*" ;;
    *.7z) shift && 7zr a "${FILE}" "$*" ;;
    *) echo "'$1' cannot be rolled via roll()" ;;
    esac
  else
    echo "usage: roll [file] [contents]"
  fi
}
