#!/bin/bash

# @todo review and refactor

function startcode() {

  unset options i
  while IFS= read -r -d $'\0' f; do
    options[i++]="${f}"
  done < <(find "${HOME}"/github.com/davidsneighbour/dotfiles/workspaces/ -maxdepth 1 -type f -name "*.code-workspace" -print0 | sort -z)

  # shellcheck disable=SC2154
  select opt in "${options[@]}" "Stop the script"; do
    case ${opt} in
    *.code-workspace)
      echo "Starting VSCode with ${opt}."
      code "${opt}"
      break
      ;;
    "Stop the script")
      break
      ;;
    *)
      echo "This is not a valid selection"
      ;;
    esac
  done

}
