#!/bin/bash

function up() {
  if [ -z "$1" ]; then
    cd ..
    return
  fi
  local levels=$1
  local result="."
  while [ "${levels}" -gt 0 ]; do
    result=${result}/..
    ((levels--))
  done
  cd "${result}" || exit
}
