#!/bin/bash

# @todo review and refactor

function g_ignore() {
  curl -sL https://www.toptal.com/developers/gitignore/api/$@
}

function g_ignore_list() {
  curl -sL https://www.toptal.com/developers/gitignore/api/list
}
