---
services:
  stirling-pdf:
    # secretlint-disable-next-line @secretlint/secretlint-rule-secp256k1-privatekey
    image: stirlingtools/stirling-pdf:2.14.2-fat@sha256:aa91c68b85992986302fbdb6735f2c0824e329304e43c814a9b77c9dd0dbe410
    container_name: stirling-pdf
    ports:
      - '3010:8080'
    volumes:
      - ./data:/configs
      - ./logs:/logs
      - ./pipeline:/pipeline
      - ./tessdata:/usr/share/tessdata
    environment:
      SYSTEM_DEFAULTLOCALE: en-GB
    restart: unless-stopped
