---
services:
  stirling-pdf:
    # secretlint-disable-next-line @secretlint/secretlint-rule-secp256k1-privatekey
    image: stirlingtools/stirling-pdf:2.14.3-fat@sha256:444c2a995e5266e585cbc22d9613d5b4c11c8ea6ac486a9a05869b55d1775f6a
    container_name: stirling-pdf
    ports:
      - '3010:8080'
    volumes:
      - ./data:/configs
      - ./logs:/logs
      - ./pipeline:/pipeline
      - ./tessdata:/usr/share/tessdata
    environment:
      SYSTEM_DEFAULTLOCALE: en-GB
    restart: unless-stopped
