---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: sh-github.png
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/
    - YouTube:
        - abbr: YT
          icon: sh-youtube.png
          href: https://youtube.com/

- Tools:
    - Calendar:
        - icon: sh-google-calendar.png
          href: https://calendar.google.com/calendar/u/0/r
    - Keep:
        - abbr: KP
          icon: sh-google-keep.png
          href: https://keep.google.com/u/0/
    - Tracking Flash:
        - abbr: FL
          href: https://www.flashexpress.com/fle/tracking
