#!/usr/bin/env bash

# terminate already running bar instances
killall -q polybar

# wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# launch new bars
polybar  -c "${HOME}"/.config/polybar/config.ini top 2>&1 | tee -a "${HOME}"/polybar-top.log & disown
polybar  -c "${HOME}"/.config/polybar/config.ini bottom 2>&1 | tee -a "${HOME}"/polybar-bottom.log & disown
