---
name: Generate GitHub Skyline

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 2 * *'
  workflow_dispatch:

permissions: {}

jobs:
  generate-skyline:
    name: Generate GitHub Skyline STL
    runs-on: ubuntu-latest

    concurrency:
      group: skyline-generation
      cancel-in-progress: true

    permissions:
      contents: write  # To push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24

      - name: Install gh-skyline extension
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install github/gh-skyline

      - name: Calculate year and generate skyline
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          year="$(date --date="$(date +%Y-%m-02) -1 month" +%Y)"
          filename="assets/gh-stl/davidsneighbour-${year}-github-skyline.stl"
          repo_owner="$(gh repo view --json owner --jq '.owner.login')"

          mkdir -p "$(dirname "${filename}")"

          gh skyline \
            --user "${repo_owner}" \
            --output "${filename}" \
            --year "${year}"

          {
            echo "FILENAME=${filename}"
            echo "YEAR=${year}"
            echo "REPO_OWNER=${repo_owner}"
          } >> "${GITHUB_ENV}"

      - name: Set up Git user from repo
        run: |
          set -euo pipefail

          user_email="${REPO_OWNER}@users.noreply.github.com"

          git config user.name "${REPO_OWNER}"
          git config user.email "${user_email}"

      - name: Commit and push changes
        run: |
          set -euo pipefail

          if [[ -n "$(git status --porcelain)" ]]; then
            git add "${FILENAME}"
            git commit -m "chore(assets): update skyline stats for ${YEAR}"
            git push
          else
            echo "No changes to commit. Exiting."
          fi
